const lessonTitle = "一生的欠条";

const lessonData = [
    // ===== 第 1 段 =====
    ["大学毕业", "dà xué bì yè", "University graduated", "Lulus universiti"],
    ["那年", "nà nián", "that year", "tahun itu"],
    ["，", "", "", ""],
    ["父亲", "fù qīn", "father", "ayah"],
    ["求亲告友", "qiú qīn gào yǒu", "begged relatives and friends", "meminta tolong saudara-mara"],
    ["，", "", "", ""],
    ["在家乡小城", "zài jiā xiāng xiǎo chéng", "in my hometown small city", "di bandar kecil kampung halaman"],
    ["给我找了份", "gěi wǒ zhǎo le fèn", "found me a", "mencarikan saya"],
    ["他认为", "tā rèn wéi", "he thought", "dia fikir"],
    ["蛮体面的工作", "mán tǐ miàn de gōng zuò", "quite decent job", "kerja yang agak baik"],
    ["，", "", "", ""],
    ["我却", "wǒ què", "but I", "tetapi saya"],
    ["毫不犹豫地", "háo bù yóu yù de", "without hesitation", "tanpa teragak-agak"],
    ["放弃了", "fàng qì le", "gave up", "melepaskan"],
    ["，", "", "", ""],
    ["决定", "jué dìng", "decided", "memutuskan"],
    ["到外面", "dào wài miàn", "to go out", "ke luar"],
    ["闯一闯", "chuǎng yì chuǎng", "to venture out", "mencuba nasib"],
    ["。", "", "", ""],
    ["那晚", "nà wǎn", "That night", "Malam itu"],
    ["，", "", "", ""],
    ["我和父亲", "wǒ hé fù qīn", "my father and I", "saya dan ayah"],
    ["深谈", "shēn tán", "had a deep talk", "berbincang panjang"],
    ["，", "", "", ""],
    ["描绘", "miáo huì", "described", "menggambarkan"],
    ["自己的", "zì jǐ de", "my", "saya punya"],
    ["理想抱负", "lǐ xiǎng bào fù", "ideals and aspirations", "cita-cita dan aspirasi"],
    ["。", "", "", ""],
    ["父亲", "fù qīn", "Father", "Ayah"],
    ["说我", "shuō wǒ", "said I", "berkata saya"],
    ["心比天高", "xīn bǐ tiān gāo", "had ambitions too high", "angan-angan terlalu tinggi"],
    ["，", "", "", ""],
    ["母亲", "mǔ qīn", "mother", "ibu"],
    ["则", "zé", "while", "pula"],
    ["在一旁", "zài yī páng", "at the side", "di sisi"],
    ["抹眼泪", "mǒ yǎn lèi", "wiped tears", "menyapu air mata"],
    ["，", "", "", ""],
    ["都", "dōu", "both", "kedua-duanya"],
    ["苦口婆心", "kǔ kǒu pó xīn", "earnestly", "dengan bersungguh-sungguh"],
    ["地劝我留下", "de quàn wǒ liú xià", "urged me to stay", "memujuk saya tinggal"],
    ["，", "", "", ""],
    ["我却", "wǒ què", "but I", "tetapi saya"],
    ["冥顽不化", "míng wán bù huà", "stubborn", "keras kepala"],
    ["，", "", "", ""],
    ["非要", "fēi yào", "insisted on", "mesti"],
    ["“", "", "", ""],
    ["走出去", "zǒu chū qù", "go out", "pergi keluar"],
    ["”", "", "", ""],
    ["不可", "bù kě", "no matter what", "juga"],
    ["。", "", "", ""],

    ["\n", "", "", ""], // 👈 第 2 段

    ["父亲", "fù qīn", "Father", "Ayah"],
    ["终于", "zhōng yú", "finally", "akhirnya"],
    ["问", "wèn", "asked", "bertanya"],
    ["：", "", "", ""],
    ["“", "", "", ""],
    ["你决定", "nǐ jué dìng", "Have you decided", "Awak sudah putuskan"],
    ["去哪里呢", "qù nǎ lǐ ne", "where to go", "hendak ke mana"],
    ["？”", "", "", ""],
    ["我思虑半天", "wǒ sī lǜ bàn tiān", "I thought for a long time", "Saya berfikir lama"],
    ["，", "", "", ""],
    ["摇摇头", "yáo yáo tóu", "shook my head", "geleng kepala"],
    ["。", "", "", ""],
    ["父亲", "fù qīn", "Father", "Ayah"],
    ["抽着", "chōu zhe", "smoked", "menghisap"],
    ["劣质烟", "liè zhì yān", "cheap cigarettes", "rokok murah"],
    ["，", "", "", ""],
    ["良久", "liáng jiǔ", "for a long time", "lama"],
    ["，", "", "", ""],
    ["才", "cái", "only then", "baru"],
    ["一字一顿地说", "yī zì yī dùn de shuō", "said slowly word by word", "berkata dengan perlahan"],
    ["：", "", "", ""],
    ["“", "", "", ""],
    ["儿大不由爹呀", "ér dà bù yóu diē ya", "A son grows up and no longer obeys his father", "Anak sudah besar tidak ikut ayah"],
    ["，", "", "", ""],
    ["你已经是", "nǐ yǐ jīng shì", "you are already", "awak sudah"],
    ["成年人了", "chéng nián rén le", "an adult", "dewasa"],
    ["，", "", "", ""],
    ["以后的路", "yǐ hòu de lù", "the road ahead", "jalan di hadapan"],
    ["怎么走", "zěn me zǒu", "how to walk", "macam mana nak jalan"],
    ["自己看着办吧", "zì jǐ kàn zhe bàn ba", "you decide for yourself", "awak sendiri fikirkan"],
    ["。", "", "", ""],
    ["”", "", "", ""],
    ["父亲同意了", "fù qīn tóng yì le", "Father agreed", "Ayah bersetuju"],
    ["！", "", "", ""],
    ["那一刻", "nà yí kè", "At that moment", "Pada masa itu"],
    ["，", "", "", ""],
    ["我为父亲", "wǒ wèi fù qīn", "I for my father's", "Saya untuk ayah punya"],
    ["无奈的妥协", "wú nài de tuǒ xié", "helpless compromise", "persetujuan yang terpaksa"],
    ["和", "hé", "and", "dan"],
    ["“", "", "", ""],
    ["支持", "zhī chí", "support", "sokongan"],
    ["”", "", "", ""],
    ["而", "ér", "", ""],
    ["感激涕零", "gǎn jī tì líng", "deeply grateful", "sangat berterima kasih"],
    ["，", "", "", ""],
    ["默默发誓", "mò mò fā shì", "silently vowed", "berazam dalam hati"],
    ["，", "", "", ""],
    ["一定", "yí dìng", "definitely", "pasti"],
    ["不让父母失望", "bù ràng fù mǔ shī wàng", "not to disappoint my parents", "tidak mengecewakan ibu bapa"],
    ["！", "", "", ""],

    ["\n", "", "", ""], // 👈 第 3 段

    ["第二天一早", "dì èr tiān yī zǎo", "Early the next morning", "Keesokan paginya"],
    ["，", "", "", ""],
    ["我收拾好", "wǒ shōu shí hǎo", "I packed", "Saya mengemas"],
    ["简单的行囊", "jiǎn dān de xíng náng", "simple luggage", "beg ringkas"],
    ["，", "", "", ""],
    ["踌躇再三", "chóu chú zài sān", "hesitated again and again", "teragak-agak"],
    ["，", "", "", ""],
    ["还是", "hái shì", "still", "masih"],
    ["硬着头皮", "yìng zhe tóu pí", "plucked up courage", "memberanikan diri"],
    ["向父亲", "xiàng fù qīn", "to ask my father", "kepada ayah"],
    ["索要路费", "suǒ yào lù fèi", "asked for travel expenses", "meminta belanja jalan"],
    ["。", "", "", ""],
    ["从小学", "cóng xiǎo xué", "From primary school", "Dari sekolah rendah"],
    ["到大学毕业", "dào dà xué bì yè", "to university graduation", "hingga tamat universiti"],
    ["，", "", "", ""],
    ["十几年里", "shí jǐ nián lǐ", "for over ten years", "lebih sepuluh tahun"],
    ["，", "", "", ""],
    ["我不知", "wǒ bù zhī", "I didn't know", "Saya tidak tahu"],
    ["向父亲", "xiàng fù qīn", "from my father", "daripada ayah"],
    ["伸手要了", "shēn shǒu yào le", "asked for", "meminta"],
    ["多少次钱", "duō shǎo cì qián", "money many times", "wang berkali-kali"],
    ["，", "", "", ""],
    ["但总觉得", "dàn zǒng jué de", "but always felt", "tetapi selalu rasa"],
    ["都是", "dōu shì", "it was", "semuanya"],
    ["天经地义的", "tiān jīng dì yì de", "only natural", "sudah menjadi lumrah"],
    ["，", "", "", ""],
    ["唯有这一次", "wéi yǒu zhè yí cì", "only this time", "hanya kali ini"],
    ["，", "", "", ""],
    ["我心里", "wǒ xīn lǐ", "in my heart", "dalam hati saya"],
    ["特别发虚", "tè bié fā xū", "felt especially guilty", "berasa sangat bersalah"],
    ["。", "", "", ""],
    ["我劝自己说", "wǒ quàn zì jǐ shuō", "I told myself", "Saya berkata pada diri sendiri"],
    ["：", "", "", ""],
    ["“", "", "", ""],
    ["这是", "zhè shì", "This is", "Ini adalah"],
    ["最后一次", "zuì hòu yí cì", "the last time", "kali terakhir"],
    ["向父亲伸手要钱", "xiàng fù qīn shēn shǒu yào qián", "asking father for money", "minta wang daripada ayah"],
    ["！”", "", "", ""],

    ["\n", "", "", ""], // 👈 第 4 段

    ["于是", "yú shì", "So", "Maka"],
    ["，", "", "", ""],
    ["我怯怯地", "wǒ qiè qiè de", "I timidly", "Saya dengan malu-malu"],
    ["去找父亲", "qù zhǎo fù qīn", "went to find my father", "pergi mencari ayah"],
    ["，", "", "", ""],
    ["可是", "kě shì", "but", "tetapi"],
    ["屋里屋外", "wū lǐ wū wài", "inside and outside the house", "dalam dan luar rumah"],
    ["到处找", "dào chù zhǎo", "searched everywhere", "cari di merata tempat"],
    ["都找不到", "dōu zhǎo bù dào", "couldn't find him", "tidak jumpa"],
    ["。", "", "", ""],
    ["正在做早饭的", "zhèng zài zuò zǎo fàn de", "Who was making breakfast", "Yang sedang menyediakan sarapan"],
    ["母亲", "mǔ qīn", "mother", "ibu"],
    ["戚然地说", "qī rán de shuō", "said sadly", "berkata dengan sedih"],
    ["：", "", "", ""],
    ["“", "", "", ""],
    ["你父亲", "nǐ fù qīn", "Your father", "Ayah awak"],
    ["一早就", "yī zǎo jiù", "early in the morning", "awal pagi lagi"],
    ["到集镇上", "dào jí zhèn shàng", "went to the market town", "pergi ke pekan"],
    ["给你寻钱去了", "gěi nǐ xún qián qù le", "to find money for you", "mencari wang untuk awak"],
    ["。", "", "", ""],
    ["出门在外", "chū mén zài wài", "Away from home", "Di perantauan"],
    ["，", "", "", ""],
    ["人地两生", "rén dì liǎng shēng", "unfamiliar with people and places", "orang dan tempat asing"],
    ["，", "", "", ""],
    ["没钱咋行", "méi qián zǎ xíng", "can't do without money", "tak boleh tanpa wang"],
    ["。", "", "", ""],
    ["可咱家的情况", "kě zán jiā de qíng kuàng", "But our family's situation", "Tetapi keadaan keluarga kita"],
    ["你也知道", "nǐ yě zhī dào", "you also know", "awak pun tahu"],
    ["，", "", "", ""],
    ["为了给你找工作", "wèi le gěi nǐ zhǎo gōng zuò", "to find you a job", "untuk carikan awak kerja"],
    ["，", "", "", ""],
    ["家底已掏空了", "jiā dǐ yǐ tāo kōng le", "we've exhausted our savings", "wang simpanan sudah habis"],
    ["。", "", "", ""],
    ["”", "", "", ""],
    ["母亲说着", "mǔ qīn shuō zhe", "Mother said", "Ibu berkata"],
    ["，", "", "", ""],
    ["皲裂的双手", "jūn liè de shuāng shǒu", "chapped hands", "tangan yang pecah-pecah"],
    ["仍在", "réng zài", "still in", "masih dalam"],
    ["冰凉的水盆里", "bīng liáng de shuǐ pén lǐ", "in the cold water basin", "dalam besen air sejuk"],
    ["搓洗着", "cuō xǐ zhe", "washing", "membasuh"],
    ["红薯", "hóng shǔ", "sweet potatoes", "ubi keledek"],
    ["，", "", "", ""],
    ["眼圈红红的", "yǎn quān hóng hóng de", "red-rimmed eyes", "mata merah"],
    ["，", "", "", ""],
    ["有些浮肿", "yǒu xiē fú zhǒng", "somewhat swollen", "agak bengkak"],
    ["。", "", "", ""],
    ["我不知道", "wǒ bù zhī dào", "I didn't know", "Saya tidak tahu"],
    ["该如何", "gāi rú hé", "how to", "bagaimana hendak"],
    ["抚慰母亲", "fǔ wèi mǔ qīn", "comfort my mother", "menghiburkan ibu"],
    ["，", "", "", ""],
    ["只能", "zhǐ néng", "could only", "hanya boleh"],
    ["木然地站着", "mù rán de zhàn zhe", "stand there blankly", "berdiri terdiam"],
    ["，", "", "", ""],
    ["心如刀绞", "xīn rú dāo jiǎo", "heartbroken", "hati bagai ditusuk pisau"],
    ["。", "", "", ""],

    ["\n", "", "", ""], // 👈 第 5 段

    ["父亲回来时", "fù qīn huí lái shí", "When father returned", "Apabila ayah pulang"],
    ["已是半晌", "yǐ shì bàn shǎng", "it was already late morning", "sudah agak lewat"],
    ["，", "", "", ""],
    ["身后", "shēn hòu", "behind him", "di belakangnya"],
    ["还跟着", "hái gēn zhe", "was following", "masih diikuti"],
    ["一个人", "yí gè rén", "a person", "seorang"],
    ["，", "", "", ""],
    ["原来是个粮贩", "yuán lái shì ge liáng fàn", "it turned out to be a grain dealer", "rupanya seorang peniaga bijirin"],
    ["。", "", "", ""],
    ["父亲", "fù qīn", "Father", "Ayah"],
    ["要卖家中的", "yào mài jiā zhōng de", "wanted to sell the family's", "hendak menjual"],
    ["麦子", "mài zi", "wheat", "gandum"],
    ["。", "", "", ""],
    ["那几年", "nà jǐ nián", "Those years", "Beberapa tahun itu"],
    ["丰产不丰收", "fēng chǎn bù fēng shōu", "good harvest but poor returns", "hasil tuaian baik tapi pendapatan rendah"],
    ["，", "", "", ""],
    ["粮食贱得要命", "liáng shi jiàn de yào mìng", "grain was extremely cheap", "harga bijirin sangat murah"],
    ["，", "", "", ""],
    ["父亲一直", "fù qīn yī zhí", "Father had always", "Ayah sentiasa"],
    ["舍不得卖", "shě bu de mài", "reluctant to sell", "sayang nak menjual"],
    ["。", "", "", ""],
    ["可是那天", "kě shì nà tiān", "But that day", "Tetapi hari itu"],
    ["，", "", "", ""],
    ["父亲一下子", "fù qīn yī xià zi", "father suddenly", "ayah sekaligus"],
    ["卖了几千斤", "mài le jǐ qiān jīn", "sold several thousand catties", "menjual beberapa ribu kati"],
    ["，", "", "", ""],
    ["装了整整一", "zhuāng le zhěng zhěng yī", "filled an entire", "memuatkan satu"],
    ["三轮车", "sān lún chē", "tricycle", "trikel"],
    ["。", "", "", ""],

    ["\n", "", "", ""], // 👈 第 6 段

    ["还没等我开口", "hái méi děng wǒ kāi kǒu", "Before I could speak", "Sebelum sempat saya buka mulut"],
    ["，", "", "", ""],
    ["父亲", "fù qīn", "father", "ayah"],
    ["就把", "jiù bǎ", "already", "terus"],
    ["两千元", "liǎng qiān yuán", "two thousand yuan", "dua ribu yuan"],
    ["卖粮款", "mài liáng kuǎn", "grain money", "wang hasil jualan bijirin"],
    ["交到了", "jiāo dào le", "handed to", "memberikan kepada"],
    ["我手里", "wǒ shǒu lǐ", "my hand", "tangan saya"],
    ["，", "", "", ""],
    ["我感激涕零", "wǒ gǎn jī tì líng", "I was deeply grateful", "Saya sangat berterima kasih"],
    ["，", "", "", ""],
    ["讷讷不能言", "nè nè bù néng yán", "speechless", "tergagap tidak dapat berkata-kata"],
    ["。", "", "", ""],
    ["可出乎我意料的是", "kě chū hū wǒ yì liào de shì", "But what was unexpected", "Tetapi yang di luar jangkaan"],
    ["，", "", "", ""],
    ["父亲", "fù qīn", "father", "ayah"],
    ["竟然", "jìng rán", "unexpectedly", "rupanya"],
    ["板着脸", "bǎn zhe liǎn", "with a stern face", "dengan muka keras"],
    ["，", "", "", ""],
    ["冷冷地说", "lěng lěng de shuō", "said coldly", "berkata dengan dingin"],
    ["：", "", "", ""],
    ["“", "", "", ""],
    ["写个欠条", "xiě ge qiàn tiáo", "Write an IOU", "Tulis nota hutang"],
    ["，", "", "", ""],
    ["这钱是借给你的", "zhè qián shì jiè gěi nǐ de", "this money is lent to you", "wang ini dipinjamkan kepadamu"],
    ["。", "", "", ""],
    ["你已经长大了", "nǐ yǐ jīng zhǎng dà le", "you've grown up", "awak sudah dewasa"],
    ["，", "", "", ""],
    ["该自己负责自己了", "gāi zì jǐ fù zé zì jǐ le", "should be responsible for yourself", "patut bertanggungjawab sendiri"],
    ["！”", "", "", ""],
    ["他语气果断", "tā yǔ qì guǒ duàn", "His tone was firm", "Nada suaranya tegas"],
    ["，", "", "", ""],
    ["不容置疑", "bù róng zhì yí", "leaving no room for doubt", "tidak boleh diragui"],
    ["。", "", "", ""],
    ["我目瞪口呆", "wǒ mù dèng kǒu dāi", "I was stunned", "Saya terdiam"],
    ["地看着父亲", "de kàn zhe fù qīn", "looking at my father", "memandang ayah"],
    ["，", "", "", ""],
    ["像看一个陌生人", "xiàng kàn yí ge mò shēng rén", "like looking at a stranger", "seperti melihat orang asing"],
    ["，", "", "", ""],
    ["难以置信", "nán yǐ zhì xìn", "unbelievable", "sukar dipercayai"],
    ["。", "", "", ""],
    ["可是父亲", "kě shì fù qīn", "But father", "Tetapi ayah"],
    ["已经", "yǐ jīng", "already", "sudah"],
    ["拿来了", "ná lái le", "brought", "mengambil"],
    ["纸和笔", "zhǐ hé bǐ", "paper and pen", "kertas dan pen"],
    ["，", "", "", ""],
    ["摊在桌上", "tān zài zhuō shàng", "spread on the table", "terbentang di atas meja"],
    ["。", "", "", ""],
    ["父亲的", "fù qīn de", "Father's", "Ayah punya"],
    ["不近人情", "bù jìn rén qíng", "inhumanity", "tidak berperikemanusiaan"],
    ["，", "", "", ""],
    ["让我失望", "ràng wǒ shī wàng", "made me disappointed", "membuatkan saya kecewa"],
    ["到了极点", "dào le jí diǎn", "to the extreme", "sangat kecewa"],
    ["，", "", "", ""],
    ["内心", "nèi xīn", "in my heart", "dalam hati"],
    ["五味杂陈", "wǔ wèi zá chén", "mixed feelings", "perasaan bercampur baur"],
    ["。", "", "", ""],
    ["就要离家远走", "jiù yào lí jiā yuǎn zǒu", "About to leave home", "Hendak meninggalkan rumah"],
    ["，", "", "", ""],
    ["父亲一句", "fù qīn yī jù", "not a single", "ayah tiada"],
    ["祝福和叮咛的话", "zhù fú hé dīng níng de huà", "blessing or caring word", "ucapan restu dan pesanan"],
    ["都没有", "dōu méi yǒu", "didn't have", "langsung tiada"],
    ["，", "", "", ""],
    ["只让我", "zhǐ ràng wǒ", "only let me", "hanya membiarkan saya"],
    ["留一张", "liú yì zhāng", "leave a", "tinggalkan sehelai"],
    ["冷冰冰的欠条", "lěng bīng bīng de qiàn tiáo", "cold IOU", "nota hutang yang dingin"],
    ["！", "", "", ""],

    ["\n", "", "", ""], // 👈 第 7 段

    ["恼恨", "nǎo hèn", "Anger", "Kemarahan"],
    ["、", "", "", ""],
    ["气愤", "qì fèn", "resentment", "geram"],
    ["一并涌上心头", "yí bìng yǒng shàng xīn tóu", "flooded my heart", "melanda hati"],
    ["，", "", "", ""],
    ["我抓起笔", "wǒ zhuā qǐ bǐ", "I grabbed the pen", "Saya meraih pen"],
    ["，", "", "", ""],
    ["以最快的速度", "yǐ zuì kuài de sù dù", "as fast as possible", "dengan secepat mungkin"],
    ["写下欠条", "xiě xià qiàn tiáo", "wrote the IOU", "menulis nota hutang"],
    ["，", "", "", ""],
    ["头也不回地走了", "tóu yě bù huí de zǒu le", "left without looking back", "pergi tanpa menoleh"],
    ["，", "", "", ""],
    ["泪水流了满脸", "lèi shuǐ liú le mǎn liǎn", "tears streaming down my face", "air mata mengalir di pipi"],
    ["，", "", "", ""],
    ["但更憋着一股劲", "dàn gèng biē zhe yì gǔ jìn", "but more determined", "tetapi lebih berazam"],
    ["：", "", "", ""],
    ["一定要", "yí dìng yào", "must", "mesti"],
    ["尽快赎回欠条", "jǐn kuài shú huí qiàn tiáo", "redeem the IOU as soon as possible", "tebus nota hutang secepat mungkin"],
    ["，", "", "", ""],
    ["哪怕再难", "nǎ pà zài nán", "no matter how difficult", "walaupun susah"],
    ["，", "", "", ""],
    ["让父亲看看", "ràng fù qīn kàn kan", "let father see", "biar ayah lihat"],
    ["儿子不是孬种", "ér zi bú shì nào zhǒng", "his son is not a coward", "anak bukan pengecut"],
    ["！", "", "", ""],

    ["\n", "", "", ""], // 👈 第 8 段

    ["我辗转", "wǒ zhǎn zhuǎn", "I wandered", "Saya merantau"],
    ["漂到了", "piāo dào le", "drifted to", "sampai ke"],
    ["省城", "shěng chéng", "provincial capital", "ibu negeri"],
    ["。", "", "", ""],
    ["一天", "yì tiān", "One day", "Satu hari"],
    ["、", "", "", ""],
    ["两天", "liǎng tiān", "two days", "dua hari"],
    ["、", "", "", ""],
    ["三天", "sān tiān", "three days", "tiga hari"],
    ["……", "", "", ""],
    ["我像一只", "wǒ xiàng yì zhī", "I was like a", "Saya seperti seekor"],
    ["无头苍蝇", "wú tóu cāng ying", "headless fly", "lalat tanpa kepala"],
    ["在这个城市里", "zài zhè ge chéng shì lǐ", "in this city", "di bandar ini"],
    ["东闯西撞", "dōng chuǎng xī zhuàng", "bumped around", "merayau-rayau"],
    ["。", "", "", ""],
    ["人才市场", "rén cái shì chǎng", "Talent market", "Pasaran bakat"],
    ["、", "", "", ""],
    ["街头广告", "jiē tóu guǎng gào", "street advertisements", "iklan jalanan"],
    ["、", "", "", ""],
    ["报纸招聘", "bào zhǐ zhāo pìn", "newspaper recruitment", "pengambilan akhbar"],
    ["，", "", "", ""],
    ["不放过", "bù fàng guò", "didn't miss", "tidak melepaskan"],
    ["任何一次希望", "rèn hé yí cì xī wàng", "any hope", "sebarang harapan"],
    ["。", "", "", ""],

    ["\n", "", "", ""], // 👈 第 9 段

    ["一个星期后", "yí ge xīng qī hòu", "A week later", "Seminggu kemudian"],
    ["，", "", "", ""],
    ["凭着自己的", "píng zhe zì jǐ de", "with my own", "dengan"],
    ["一支笔", "yì zhī bǐ", "pen", "pen"],
    ["，", "", "", ""],
    ["我在一家", "wǒ zài yì jiā", "I found a", "saya di sebuah"],
    ["广告公司", "guǎng gào gōng sī", "advertising company", "syarikat pengiklanan"],
    ["谋得了", "móu dé le", "got", "mendapat"],
    ["一份", "yí fèn", "a", "satu"],
    ["文案的工作", "wén àn de gōng zuò", "copywriting job", "kerja penulisan"],
    ["。", "", "", ""],
    ["在工作之余", "zài gōng zuò zhī yú", "In my spare time", "Di waktu lapang"],
    ["，", "", "", ""],
    ["我没忘", "wǒ méi wàng", "I didn't forget", "Saya tidak lupa"],
    ["给自己充电", "gěi zì jǐ chōng diàn", "to improve myself", "untuk menambah ilmu"],
    ["，", "", "", ""],
    ["时有文章", "shí yǒu wén zhāng", "often had articles", "kadang-kadang ada artikel"],
    ["在省内外的报刊上", "zài shěng nèi wài de bào kān shàng", "in newspapers inside and outside the province", "di akhbar dalam dan luar provinsi"],
    ["发表", "fā biǎo", "published", "disiarkan"],
    ["。", "", "", ""],
    ["半年后", "bàn nián hòu", "Half a year later", "Setengah tahun kemudian"],
    ["，", "", "", ""],
    ["我又", "wǒ yòu", "I again", "saya lagi"],
    ["跳槽到了", "tiào cáo dào le", "switched jobs to", "bertukar kerja ke"],
    ["一家报社", "yì jiā bào shè", "a newspaper office", "sebuah pejabat akhbar"],
    ["。", "", "", ""],
    ["这期间", "zhè qī jiān", "During this period", "Dalam tempoh ini"],
    ["，", "", "", ""],
    ["我只", "wǒ zhǐ", "I only", "saya hanya"],
    ["应景式地", "yìng jǐng shì de", "perfunctorily", "sekadar"],
    ["往家里", "wǎng jiā lǐ", "to home", "ke rumah"],
    ["打了两次电话", "dǎ le liǎng cì diàn huà", "called twice", "menelefon dua kali"],
    ["，", "", "", ""],
    ["每次都以", "měi cì dōu yǐ", "each time using", "setiap kali dengan alasan"],
    ["工作忙为借口", "gōng zuò máng wéi jiè kǒu", "busy work as an excuse", "sibuk kerja sebagai alasan"],
    ["匆匆挂断", "cōng cōng guà duàn", "hurriedly hung up", "tergesa-gesa menutup talian"],
    ["，", "", "", ""],
    ["心里仍然", "xīn lǐ réng rán", "still in my heart", "dalam hati masih"],
    ["对父亲", "duì fù qīn", "to my father", "terhadap ayah"],
    ["满怀怨恨", "mǎn huái yuàn hèn", "full of resentment", "penuh dengan dendam"],
    ["。", "", "", ""],

    ["\n", "", "", ""], // 👈 第 10 段

    ["到报社", "dào bào shè", "After arriving at the newspaper office", "Setelah sampai ke pejabat akhbar"],
    ["发了", "fā le", "received", "menerima"],
    ["第一笔工资后", "dì yī bǐ gōng zī hòu", "after receiving the first salary", "selepas menerima gaji pertama"],
    ["，", "", "", ""],
    ["我径自", "wǒ jìng zì", "I directly", "Saya terus"],
    ["回了家", "huí le jiā", "went home", "pulang ke rumah"],
    ["。", "", "", ""],
    ["父亲", "fù qīn", "Father", "Ayah"],
    ["对我的", "duì wǒ de", "to my", "terhadap saya punya"],
    ["不期而归", "bù qī ér guī", "unexpected return", "kepulangan tanpa diduga"],
    ["大感意外", "dà gǎn yì wài", "was greatly surprised", "sangat terkejut"],
    ["，", "", "", ""],
    ["一迭声问", "yī dié shēng wèn", "asked repeatedly", "bertanya berulang kali"],
    ["我在省城怎么样", "wǒ zài shěng chéng zěn me yàng", "how I was doing in the provincial capital", "bagaimana saya di ibu negeri"],
    ["，", "", "", ""],
    ["坐啥车回来的", "zuò shá chē huí lái de", "what bus I took", "naik apa balik"],
    ["，", "", "", ""],
    ["回来有急事吗", "huí lái yǒu jí shì ma", "if I had urgent business", "ada hal kecemasan pulang"],
    ["……", "", "", ""],
    ["听得我", "tīng de wǒ", "it made me", "membuatkan saya"],
    ["心烦意乱", "xīn fán yì luàn", "irritated", "rimas"],
    ["。", "", "", ""],
    ["我冷冷敷衍着", "wǒ lěng lěng fū yǎn zhe", "I coldly brushed him off", "Saya menepis dengan dingin"],
    ["，", "", "", ""],
    ["同时", "tóng shí", "at the same time", "pada masa yang sama"],
    ["郑重地", "zhèng zhòng de", "seriously", "dengan sungguh-sungguh"],
    ["掏出", "tāo chū", "took out", "mengeluarkan"],
    ["两千元钱", "liǎng qiān yuán qián", "two thousand yuan", "dua ribu yuan"],
    ["，", "", "", ""],
    ["向父亲", "xiàng fù qīn", "to my father", "kepada ayah"],
    ["索要欠条", "suǒ yào qiàn tiáo", "asked for the IOU", "meminta nota hutang"],
    ["。", "", "", ""],

    ["\n", "", "", ""], // 👈 第 11 段

    ["父亲一愣", "fù qīn yī lèng", "Father was stunned", "Ayah terkejut"],
    ["，", "", "", ""],
    ["然后", "rán hòu", "then", "kemudian"],
    ["缓缓走到里间", "huǎn huǎn zǒu dào lǐ jiān", "slowly walked to the inner room", "perlahan-lahan berjalan ke bilik dalam"],
    ["，", "", "", ""],
    ["打开箱子", "dǎ kāi xiāng zi", "opened the box", "membuka peti"],
    ["，", "", "", ""],
    ["从一本", "cóng yì běn", "from an", "dari sebatang"],
    ["旧书里", "jiù shū lǐ", "old book", "buku lama"],
    ["取出了", "qǔ chū le", "took out", "mengeluarkan"],
    ["那张崭新的欠条", "nà zhāng zhǎn xīn de qiàn tiáo", "that brand new IOU", "nota hutang yang masih baru"],
    ["。", "", "", ""],
    ["没等我伸出手", "méi děng wǒ shēn chū shǒu", "Before I could reach out", "Sebelum sempat saya menghulurkan tangan"],
    ["，", "", "", ""],
    ["父亲", "fù qīn", "father", "ayah"],
    ["就当面", "jiù dāng miàn", "immediately in front of me", "terus di hadapan saya"],
    ["把欠条撕了", "bǎ qiàn tiáo sī le", "tore up the IOU", "mengoyakkan nota hutang"],
    ["，", "", "", ""],
    ["又一把", "yòu yī bǎ", "and also", "dan juga"],
    ["推开我的两千元", "tuī kāi wǒ de liǎng qiān yuán", "pushed away my two thousand yuan", "menolak balik dua ribu yuan saya"],
    ["，", "", "", ""],
    ["坐了下来", "zuò le xià lái", "sat down", "duduk"],
    ["。", "", "", ""],
    ["他抽着旱烟", "tā chōu zhe hàn yān", "He smoked his pipe", "Dia menghisap paip tembakau"],
    ["，", "", "", ""],
    ["有些伤感地说", "yǒu xiē shāng gǎn de shuō", "said somewhat sadly", "berkata dengan agak sedih"],
    ["：", "", "", ""],
    ["“", "", "", ""],
    ["当时让你写欠条", "dāng shí ràng nǐ xiě qiàn tiáo", "When I asked you to write the IOU", "Masa itu suruh awak tulis nota hutang"],
    ["，", "", "", ""],
    ["也是", "yě shì", "also was", "juga"],
    ["怕你年少轻狂", "pà nǐ nián shào qīng kuáng", "afraid you were young and reckless", "takut awak muda dan gila"],
    ["，", "", "", ""],
    ["半途而废", "bàn tú ér fèi", "give up halfway", "separuh jalan berputus asa"],
    ["，", "", "", ""],
    ["逼着你", "bī zhe nǐ", "to push you", "memaksa awak"],
    ["往前走呢", "wǎng qián zǒu ne", "to move forward", "teruskan ke hadapan"],
    ["。", "", "", ""],
    ["你走时那种眼神", "nǐ zǒu shí nà zhǒng yǎn shén", "The look in your eyes when you left", "Pandangan mata awak masa pergi"],
    ["，", "", "", ""],
    ["让我心里", "ràng wǒ xīn lǐ", "made my heart", "membuatkan hati saya"],
    ["不好受到今天", "bù hǎo shòu dào jīn tiān", "uncomfortable until today", "terasa bersalah sampai sekarang"],
    ["！", "", "", ""],
    ["要说欠的", "yào shuō qiàn de", "If we talk about debt", "Kalau cakap tentang hutang"],
    ["，", "", "", ""],
    ["两千元", "liǎng qiān yuán", "two thousand yuan", "dua ribu yuan"],
    ["你以为", "nǐ yǐ wéi", "do you think", "awak fikir"],
    ["就能还清吗", "jiù néng huán qīng ma", "can pay it off", "boleh bayar habis"],
    ["？”", "", "", ""],

    ["\n", "", "", ""], // 👈 第 12 段

    ["我脸红了", "wǒ liǎn hóng le", "I blushed", "Saya muka merah"],
    ["。", "", "", ""],
    ["一张欠条", "yì zhāng qiàn tiáo", "An IOU", "Sehelai nota hutang"],
    ["就让我", "jiù ràng wǒ", "just made me", "sahaja membuatkan saya"],
    ["气愤难平", "qì fèn nán píng", "so angry", "sangat marah"],
    ["，", "", "", ""],
    ["哪能", "nǎ néng", "how could I", "mana boleh"],
    ["体谅父亲", "tǐ liàng fù qīn", "understand father's", "memahami ayah punya"],
    ["的一片苦心", "de yí piàn kǔ xīn", "good intentions", "segala usaha"],
    ["？", "", "", ""],

    ["\n", "", "", ""], // 👈 第 13 段

    ["“", "", "", ""],
    ["城里花销大", "chéng lǐ huā xiāo dà", "Living in the city is expensive", "Perbelanjaan di bandar besar"],
    ["，", "", "", ""],
    ["钱你留着", "qián nǐ liú zhe", "you keep the money", "wang awak simpan"],
    ["。", "", "", ""],
    ["孩子给父母", "hái zi gěi fù mǔ", "The best thing children can give parents", "Anak beri kepada ibu bapa"],
    ["最好的回报", "zuì hǎo de huí bào", "the best return", "balasan terbaik"],
    ["，", "", "", ""],
    ["就是", "jiù shì", "is", "ialah"],
    ["自个儿", "zì gě r", "to be", "diri sendiri"],
    ["能自立自强", "néng zì lì zì qiáng", "independent and strong", "boleh berdikari"],
    ["，", "", "", ""],
    ["过上好日子", "guò shàng hǎo rì zi", "live a good life", "hidup senang"],
    ["！”", "", "", ""],

    ["\n", "", "", ""], // 👈 第 14 段

    ["父亲说着", "fù qīn shuō zhe", "Father said", "Ayah berkata"],
    ["，", "", "", ""],
    ["用粗黑的大手", "yòng cū hēi de dà shǒu", "with his big rough dark hand", "dengan tangan besar dan kasar"],
    ["抹了抹眼角", "mǒ le mǒ yǎn jiǎo", "wiped the corners of his eyes", "menyapu hujung mata"],
    ["，", "", "", ""],
    ["让我", "ràng wǒ", "made me", "membuatkan saya"],
    ["陡然心酸", "dǒu rán xīn suān", "suddenly felt heartache", "tiba-tiba berasa sedih"],
    ["。", "", "", ""],
    ["我蹲下身去", "wǒ dūn xià shēn qù", "I squatted down", "Saya mencangkung"],
    ["，", "", "", ""],
    ["把地上的", "bǎ dì shàng de", "picked up the", "mengambil"],
    ["小纸片", "xiǎo zhǐ piàn", "paper pieces", "kertas kecil"],
    ["捡了起来", "jiǎn le qǐ lái", "pieces on the ground", "di atas tanah"],
    ["。", "", "", ""],
    ["我要把它", "wǒ yào bǎ tā", "I want to", "Saya mahu"],
    ["重新粘好", "chóng xīn zhān hǎo", "paste it back together", "lekatkan semula"],
    ["，", "", "", ""],
    ["随时带在身边", "suí shí dài zài shēn biān", "keep it with me always", "sentiasa bawa bersama"],
    ["，", "", "", ""],
    ["时刻铭记", "shí kè míng jì", "always remember", "sentiasa ingat"],
    ["这张欠条里", "zhè zhāng qiàn tiáo lǐ", "the love contained", "dalam nota hutang ini"],
    ["蕴含的", "yùn hán de", "in this IOU", "yang terkandung"],
    ["绵长的情意", "mián cháng de qíng yì", "long-lasting affection", "kasih sayang yang panjang"],
    ["。", "", "", ""],

    ["\n", "", "", ""], // 👈 出处

    ["（", "", "", ""],
    ["佚名", "yì míng", "Anonymous", "Tanpa Nama"],
    ["《", "", "", ""],
    ["一生的欠条", "yì shēng de qiàn tiáo", "A Lifetime's IOU", "Nota Hutang Seumur Hidup"],
    ["》", "", "", ""],
    ["，", "", "", ""],
    ["有", "yǒu", "with", "ada"],
    ["改动", "gǎi dòng", "adaptations", "ubah suai"],
    ["）", "", "", ""]
];
